# .streamlit/config.toml
[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
font = "sans serif"

# This enables the multipage app functionality
[server]
headless = true